### ISSUE TITLE
Unable to login using the V2 script

### ISSUE THREAD

**Issue by Sigamani301992** [ldaptive/aws-s3-sftp-azure-IdentityProvider-V2#1]
Hi @ldaptive ,

Hope you are doing well. 

I have changed from V1 script to V2 script but i received invalid user name and password error. Tried googling the error message and found that we cant authenticate a federated user using the graph API. Is it true ? We cant authenticate a federated user using the Graph API ?

 error: 'invalid_grant',  
Im using the user name and password which was working in the V1 script.

Thanks in advance.

Regards,
Sigamani S

**Comment by ldaptive** [comment]
A federated user, meaning a user outside your domain or organization, just someone you have granted access to things via your domain?

**Comment by Sigamani301992** [comment]
Hi @ldaptive , 

I understand from our AD team that we are not creating/managing users & groups in Azure AD. We create users/groups in our on prem AD and it will get replicated to Azure AD.  But the authentication was working in our V1 script. Any help on this please.

Thanks,
Sigamani S

**Comment by ldaptive** [comment]
invalid grant sounds like you don't have the functions set correctly. is this set to grant_type = 'password' ? The users that have been synced from on premise to azure, are they apart of a group that has access to the application? 

this change was another implementation that we worked on with a customer that had the exact same setup you are describing and they have no issues. 

I would troubleshoot first by adding a synced user directly to the application to validate they can login this way. If so then you should validate that the onpremise AD group membership is added to gain access to the application. send your authentication now with 'username@mydomain.com' since sftp will now handle the @ sign

**Comment by Sigamani301992** [comment]
Hi @ldaptive , 

yes grant_type is set to 'password'. And i tried to add the synced user directly to the application. But still i receive the same error message. The first level of authentication itself is getting failed.

Thanks,
Sigamani S

**Comment by ldaptive** [comment]
Can you create a user directly in azure, add them to the app and validate your authentication works with the app?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sigamani301992** [comment]
Hi @ldaptive , 

Sure im raising a ticket to my internal AD team to create a user is Azure. Once i get it ill validate and update you. 

Thanks,
Sigamani S

**Comment by ldaptive** [comment]
No updates for sometime, closing issue.
